### ISSUE TITLE
URGENT: Requiring 2FA across the Home Assistant organization November 3rd

### ISSUE THREAD

**Issue by robbiet480** [home-assistant/organization#1]
Hello!

If you have been tagged at the bottom of this issue that means that you do not currently have two factor authentication (2FA) enabled on your Github account.

In the interests of security, the Home Assistant Github organization will be enabling required 2FA on or about November 3rd, 2016. **Those that don't have 2FA enabled by November 3rd, 2016 will be removed from the repositories they have access to**. You can re-request access to repositories once you have enabled 2FA on your Github account.

**Once you have enabled 2FA on your GitHub account please put a comment on this issue stating so** just so that I know who has and has not done it by the 3rd.

Instructions for enabling 2FA on GitHub can be found [here](https://help.github.com/articles/about-two-factor-authentication/) and [here](https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/).

We thank you for your understanding in this matter and also thank you for being part of the Home Assistant contributors teams!

-- Robbie

Contributors affected:
- [x] @andythigpen
- [ ] @flyte
- [x] @happyleavesaoc
- [x] @justweb1
- [ ] @kireyeu
- [ ] @kk7ds
- [x] @miniconfig
- [x] @persandstrom
- [ ] @rhooper
- [x] @SEJeff
- [x] @sdague
- [ ] @sfam
- [x] @shaftoe
- [x] @stefan-jonasson
- [ ] @theolind
- [x] @w1ll1am23
- [x] @Xorso

**Comment by sdague** [comment]
Enabled 2FA

**Comment by justweb1** [comment]
Enabled

**Comment by w1ll1am23** [comment]
Enabled

**Comment by miniconfig** [comment]
Enabled

**Comment by stefan-jonasson** [comment]
Enabled

**Comment by andythigpen** [comment]
Enabled

**Comment by shaftoe** [comment]
Enabled

**Comment by happyleavesaoc** [comment]
Enabled

**Comment by persandstrom** [comment]
Enabled

**Comment by SEJeff** [comment]
doneski!

**Comment by robbiet480** [comment]
@sdague You had a beautiful checkmark next to your name earlier but now it's gone because GitHub says your 2FA is off again 😢

**Comment by sdague** [comment]
@robbiet480 so weird, I just set it again. I wonder if because I didn't set an SMS fallback the first time they reverted me for some reason.

Hopefully this sticks now.

**Comment by lorddaren** [comment]
Enabled.

**Comment by robbiet480** [comment]
@rhooper, @kireyeu, @theolind, @flyte, @sfam, @kk7ds,

You have been removed from the Home Assistant organization because 2FA was not enabled in time. If you want to regain access please open a new issue in this repository (obviously after enabling 2FA). No hard feelings on this, just trying to remain secure!

To everyone else, thanks for getting this done and thanks for being Home Assistant contributors.
